"use client";

import { useMemo, useState } from "react";
import { Activity, ArrowDownRight, ArrowRight, ArrowUpRight, Bell, CalendarDays, Check, CheckCheck, CheckCircle2, ChevronDown, ChevronLeft, ChevronRight, Circle, Clock3, Command, Ellipsis, Flag, FolderKanban, LayoutGrid, ListTodo, LogOut, Menu, MessageCircle, Plus, Search, Settings2, ShieldCheck, Sparkles, Target, Trash2, Users, X } from "lucide-react";

type Member = { id: number; name: string; email: string; role: string; title: string; color: string; initials: string };
type Task = { id: number; title: string; description: string; status: string; priority: string; category: string; assigneeId: number | null; dueDate: string; createdAt: string; completedAt: string | null };
type Milestone = { id: number; title: string; description: string; dueDate: string; status: string };
type Notice = { id: string; title: string; message: string; type: string; recipientId?: number | null; taskId: number | null; read: boolean; createdAt: string };
type Data = { members: Member[]; tasks: Task[]; milestones: Milestone[]; notifications: Notice[]; user: Member | null };
type Section = "Overview" | "My Tasks" | "Timeline" | "Team" | "Inbox";

const dateLabel = (value: string, options?: Intl.DateTimeFormatOptions) => new Date(value + "T12:00:00").toLocaleDateString("en-US", options ?? { month: "short", day: "numeric" });
const today = () => new Date().toISOString().slice(0, 10);
const navigation: { label: Section; icon: typeof LayoutGrid }[] = [
  { label: "Overview", icon: LayoutGrid }, { label: "My Tasks", icon: ListTodo }, { label: "Timeline", icon: CalendarDays }, { label: "Team", icon: Users }, { label: "Inbox", icon: Bell },
];
const statusName: Record<string, string> = { todo: "To do", in_progress: "In progress", done: "Completed" };

function Avatar({ person, size = "normal" }: { person?: Member; size?: "normal" | "small" | "large" }) {
  return <span className={`avatar avatar-${size}`} style={{ background: person?.color ?? "#e8e9ee" }} title={person?.name ?? "Unassigned"}>{person?.initials ?? "?"}</span>;
}
function SectionHeading({ title, subtitle, action }: { title: string; subtitle?: string; action?: React.ReactNode }) {
  return <div className="section-heading"><div><h2>{title}</h2>{subtitle && <p>{subtitle}</p>}</div>{action}</div>;
}

export default function Workspace({ initialData }: { initialData: Data }) {
  const [data, setData] = useState<Data>(initialData);
  const [section, setSection] = useState<Section>("Overview");
  const [search, setSearch] = useState("");
  const [showAuth, setShowAuth] = useState(false);
  const [showNew, setShowNew] = useState(false);
  const [selectedTask, setSelectedTask] = useState<Task | null>(null);
  const [showNotifications, setShowNotifications] = useState(false);
  const [mobileNav, setMobileNav] = useState(false);
  const [busy, setBusy] = useState(false);
  const [toast, setToast] = useState("");
  const [authEmail, setAuthEmail] = useState("olivia@vertex.demo");
  const [authPassword, setAuthPassword] = useState("demo1234");
  const [form, setForm] = useState({ title: "", description: "", assigneeId: String(initialData.members[1]?.id ?? ""), dueDate: new Date(Date.now() + 7 * 86400000).toISOString().slice(0, 10), priority: "medium", category: "Design" });
  const [edit, setEdit] = useState({ title: "", assigneeId: "", dueDate: "", priority: "medium", status: "todo" });
  const [hiddenDeadlines, setHiddenDeadlines] = useState<string[]>([]);

  const user = data.user;
  const isLead = user?.role === "lead";
  const completed = data.tasks.filter((task) => task.status === "done").length;
  const inProgress = data.tasks.filter((task) => task.status === "in_progress").length;
  const progress = data.tasks.length ? Math.round(completed / data.tasks.length * 100) : 0;
  const activeTasks = data.tasks.filter((task) => task.status !== "done");
  const unread = data.notifications.filter((notice) => !notice.read && !hiddenDeadlines.includes(notice.id)).length;
  const deadlineCount = activeTasks.filter((task) => task.dueDate <= new Date(Date.now() + 3 * 86400000).toISOString().slice(0, 10)).length;
  const filteredTasks = useMemo(() => data.tasks.filter((task) => {
    const matches = task.title.toLowerCase().includes(search.toLowerCase()) || task.category.toLowerCase().includes(search.toLowerCase()) || data.members.find((member) => member.id === task.assigneeId)?.name.toLowerCase().includes(search.toLowerCase());
    return matches && (section !== "My Tasks" || !user || isLead || task.assigneeId === user.id);
  }), [data.tasks, data.members, search, section, user, isLead]);
  const [taskFilter, setTaskFilter] = useState("All tasks");
  const visibleTasks = filteredTasks.filter((task) => taskFilter === "All tasks" || (taskFilter === "In progress" && task.status === "in_progress") || (taskFilter === "To do" && task.status === "todo") || (taskFilter === "Completed" && task.status === "done"));

  const flash = (message: string) => { setToast(message); window.setTimeout(() => setToast(""), 3500); };
  async function refresh() { const response = await fetch("/api/workspace", { cache: "no-store" }); if (response.ok) setData(await response.json()); }
  async function act(payload: Record<string, unknown>, success: string) {
    setBusy(true);
    try {
      const response = await fetch("/api/workspace", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) });
      const result = await response.json();
      if (!response.ok) throw new Error(result.error || "Something went wrong.");
      setData(result); flash(success); return true;
    } catch (error) { flash(error instanceof Error ? error.message : "Something went wrong."); return false; }
    finally { setBusy(false); }
  }
  async function login(event: React.FormEvent) {
    event.preventDefault(); setBusy(true);
    try {
      const response = await fetch("/api/auth", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email: authEmail, password: authPassword }) });
      const result = await response.json(); if (!response.ok) throw new Error(result.error);
      await refresh(); setShowAuth(false); flash(`Welcome back, ${result.user.name.split(" ")[0]}!`);
    } catch (error) { flash(error instanceof Error ? error.message : "Sign in failed."); }
    finally { setBusy(false); }
  }
  async function logout() { await fetch("/api/auth", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "logout" }) }); await refresh(); flash("Signed out successfully."); }
  function openTask(task: Task) { setSelectedTask(task); setEdit({ title: task.title, assigneeId: String(task.assigneeId ?? ""), dueDate: task.dueDate, priority: task.priority, status: task.status }); }
  function requestNew() { if (!isLead) { if (user) flash("Only the project lead can create tasks."); else setShowAuth(true); return; } setShowNew(true); }
  async function createTask(event: React.FormEvent) { event.preventDefault(); if (await act({ action: "createTask", ...form, assigneeId: Number(form.assigneeId) }, "Task created and teammate notified.")) { setShowNew(false); setForm({ ...form, title: "", description: "" }); } }
  async function saveTask(event: React.FormEvent) { event.preventDefault(); if (!selectedTask) return; if (await act({ action: "updateTask", taskId: selectedTask.id, ...edit, assigneeId: Number(edit.assigneeId) }, "Task updated successfully.")) setSelectedTask(null); }
  async function readNotice(notice: Notice) { if (notice.id.startsWith("deadline-")) setHiddenDeadlines((current) => [...current, notice.id]); else if (user) await act({ action: "readNotification", notificationId: notice.id }, "Notification marked as read."); if (notice.taskId) { const task = data.tasks.find((item) => item.id === notice.taskId); if (task) openTask(task); } setShowNotifications(false); }

  const contribution = data.members.map((member) => { const assigned = data.tasks.filter((task) => task.assigneeId === member.id); return { member, total: assigned.length, done: assigned.filter((task) => task.status === "done").length }; });
  const navTo = (item: Section) => { setSection(item); setMobileNav(false); setSearch(""); setTaskFilter("All tasks"); };

  return <div className="app-shell">
    {mobileNav && <button className="mobile-scrim" onClick={() => setMobileNav(false)} aria-label="Close menu" />}
    <aside className={`sidebar ${mobileNav ? "sidebar-open" : ""}`}>
      <div className="brand"><div className="brand-mark"><span></span><span></span><span></span><span></span></div><span>vertex<span className="brand-dot">.</span></span></div>
      <div className="workspace-picker"><span className="workspace-symbol">S</span><span className="workspace-name"><strong>Studio North</strong><small>Pro workspace</small></span><ChevronDown size={15} /></div>
      <div className="side-label">WORKSPACE</div>
      <nav className="side-nav">{navigation.map(({ label, icon: Icon }) => <button key={label} className={`nav-item ${section === label ? "active" : ""}`} onClick={() => navTo(label)}><Icon size={18} strokeWidth={1.9} /><span>{label}</span>{label === "Inbox" && unread > 0 && <em>{unread}</em>}</button>)}</nav>
      <div className="side-label side-label-projects">YOUR PROJECTS <button title="New task" onClick={requestNew}><Plus size={17} /></button></div>
      <button className="project-nav active-project" onClick={() => navTo("Overview")}><span className="project-dot purple" />Website Redesign</button>
      <div className="sidebar-spacer" />
      <div className="help-card"><span className="help-icon"><Sparkles size={17} /></span><strong>Keep things moving</strong><p>Great work happens when everyone is on the same page.</p><button onClick={() => navTo("Timeline")}>View timeline <ArrowRight size={14} /></button></div>
      <div className="sidebar-user" onClick={() => user ? logout() : setShowAuth(true)} role="button" tabIndex={0} onKeyDown={(e) => { if (e.key === "Enter") user ? logout() : setShowAuth(true); }}><Avatar person={user ?? data.members[0]} /><span><strong>{user?.name ?? "Guest preview"}</strong><small>{user?.title ?? "Sign in to collaborate"}</small></span>{user ? <LogOut size={16} /> : <ChevronRight size={16} />}</div>
    </aside>

    <main className="main-area">
      <header className="topbar"><div className="topbar-left"><button className="mobile-menu icon-button" onClick={() => setMobileNav(true)} aria-label="Open menu"><Menu size={21} /></button><span>Projects</span><ChevronRight size={15} /><strong>Website Redesign</strong></div><div className="topbar-right"><div className="search-box"><Search size={17} /><input value={search} onChange={(e) => { setSearch(e.target.value); if (e.target.value) setSection("My Tasks"); }} placeholder="Search tasks..." aria-label="Search tasks" /><kbd>⌘ K</kbd></div><div className="notification-wrap"><button className="icon-button notification-button" onClick={() => setShowNotifications(!showNotifications)} aria-label="Notifications"><Bell size={20} />{unread > 0 && <span className="notification-pip" />}</button>{showNotifications && <div className="notification-popover"><div className="popover-header"><strong>Notifications</strong><span>{unread} new</span></div>{data.notifications.slice(0, 5).map((notice) => <button key={notice.id} className={`popover-notice ${notice.read ? "is-read" : ""}`} onClick={() => readNotice(notice)}><span className={`notice-icon ${notice.type}`}><Bell size={15} /></span><span><strong>{notice.title}</strong><small>{notice.message}</small></span></button>)}<button className="popover-footer" onClick={() => { setShowNotifications(false); navTo("Inbox"); }}>View all notifications <ArrowRight size={14} /></button></div>}</div><span className="topbar-divider" /><button className="top-avatar" onClick={() => user ? logout() : setShowAuth(true)} title={user ? "Sign out" : "Sign in"}><Avatar person={user ?? data.members[0]} size="small" /></button></div></header>

      <div className="page-content">
        <div className="page-intro"><div><div className="eyebrow">PROJECT WORKSPACE <span className="eyebrow-line" /></div><h1>{section === "Overview" ? "Project overview" : section}</h1><p>{section === "Overview" ? "Here’s what’s happening with your project today." : section === "My Tasks" ? "Keep work organized and moving forward." : section === "Timeline" ? "A clear path from first idea to final launch." : section === "Team" ? "The people bringing this project to life." : "Stay on top of the latest project updates."}</p></div><div className="intro-actions">{!user && <button className="button button-light" onClick={() => setShowAuth(true)}><ShieldCheck size={16} /> Admin access</button>}<button className="button button-primary" onClick={requestNew}><Plus size={18} /> New task</button></div></div>

        {section === "Overview" && <>
          <div className="project-hero"><div className="hero-main"><div className="hero-icon"><FolderKanban size={25} strokeWidth={1.7} /></div><div><div className="hero-title-row"><h2>Website Redesign</h2><span className="status-pill"><span /> In progress</span></div><p>Refreshing our digital experience, one detail at a time.</p><div className="hero-meta"><span><CalendarDays size={15} /> {dateLabel(data.milestones[0]?.dueDate ?? today())} – {dateLabel(data.milestones.at(-1)?.dueDate ?? today(), { month: "short", day: "numeric", year: "numeric" })}</span><i /><span><Users size={15} /> {data.members.length} members</span></div></div></div><div className="hero-progress"><div className="progress-copy"><span>Overall progress</span><strong>{progress}%</strong></div><div className="progress-track"><span style={{ width: `${progress}%` }} /></div><div className="hero-progress-bottom"><div className="avatar-stack">{data.members.slice(0, 4).map((person) => <Avatar key={person.id} person={person} size="small" />)}<span className="avatar-more">+{Math.max(0, data.members.length - 4)}</span></div><button onClick={() => navTo("Team")}>View team <ArrowRight size={14} /></button></div></div></div>
          <div className="stats-grid"><div className="stat-card"><span className="stat-icon lavender"><ListTodo size={19} /></span><span className="stat-label">Total tasks</span><div className="stat-value">{data.tasks.length.toString().padStart(2, "0")} <span className="stat-trend positive"><ArrowUpRight size={13} /> All time</span></div><p>Across all project phases</p></div><div className="stat-card"><span className="stat-icon mint"><CheckCircle2 size={19} /></span><span className="stat-label">Completed</span><div className="stat-value">{completed.toString().padStart(2, "0")} <span className="stat-trend positive"><ArrowUpRight size={13} /> {progress}%</span></div><p>Tasks finished so far</p></div><div className="stat-card"><span className="stat-icon peach"><Activity size={19} /></span><span className="stat-label">In progress</span><div className="stat-value">{inProgress.toString().padStart(2, "0")} <span className="stat-trend neutral">On track</span></div><p>Currently being worked on</p></div><div className="stat-card"><span className="stat-icon rose"><Clock3 size={19} /></span><span className="stat-label">Due soon</span><div className="stat-value">{deadlineCount.toString().padStart(2, "0")} <span className="stat-trend warning">Next 3 days</span></div><p>Keep an eye on deadlines</p></div></div>
          <div className="dashboard-grid"><div className="dashboard-left"><div className="card progress-card"><SectionHeading title="Project progress" subtitle="A snapshot of how things are moving" action={<span className="select-lite">This month <ChevronDown size={14} /></span>} /><div className="chart-top"><strong>{progress}%</strong><span className="chart-change"><ArrowUpRight size={14} /> Looking good</span></div><p className="chart-description">of all tasks completed</p><div className="chart-container"><div className="chart-grid"><span>100%</span><span>75%</span><span>50%</span><span>25%</span><span>0%</span></div><svg className="chart-svg" viewBox="0 0 650 180" preserveAspectRatio="none" aria-label="Project progress trend"><defs><linearGradient id="chartFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#7866eb" stopOpacity="0.17" /><stop offset="100%" stopColor="#7866eb" stopOpacity="0" /></linearGradient></defs><path d="M0 157 C48 150 77 148 117 134 S190 128 231 104 S302 103 350 84 S418 83 465 58 S537 61 583 31 S622 30 650 17 L650 180 L0 180 Z" fill="url(#chartFill)" /><path d="M0 157 C48 150 77 148 117 134 S190 128 231 104 S302 103 350 84 S418 83 465 58 S537 61 583 31 S622 30 650 17" fill="none" stroke="#7665e9" strokeWidth="3" strokeLinecap="round" /><circle cx="583" cy="31" r="6" fill="#7665e9" stroke="white" strokeWidth="3" /></svg></div><div className="chart-months"><span>Week 1</span><span>Week 2</span><span>Week 3</span><span>Week 4</span><span>Week 5</span></div></div>
            <div className="card upcoming-card"><SectionHeading title="Upcoming tasks" subtitle="What’s next on the to-do list" action={<button className="text-action" onClick={() => navTo("My Tasks")}>View all <ArrowRight size={15} /></button>} /><div className="upcoming-list">{activeTasks.slice(0, 3).map((task) => <button className="upcoming-row" key={task.id} onClick={() => openTask(task)}><span className={`task-check ${task.status === "in_progress" ? "working" : ""}`}>{task.status === "in_progress" && <span />}</span><span className="upcoming-info"><strong>{task.title}</strong><small><span className={`category-dot ${task.category.toLowerCase()}`} />{task.category} <span className="middle-dot">·</span> Due {dateLabel(task.dueDate)}</small></span><Avatar person={data.members.find((member) => member.id === task.assigneeId)} size="small" /><ChevronRight className="row-chevron" size={17} /></button>)}{!activeTasks.length && <div className="empty-inline">All caught up! Every task is complete.</div>}</div></div></div>
          <div className="dashboard-right"><div className="card timeline-card"><SectionHeading title="Project timeline" subtitle="Key milestones at a glance" action={<button className="dots-button" onClick={() => navTo("Timeline")} aria-label="View timeline"><Ellipsis size={21} /></button>} /><div className="timeline-list">{data.milestones.map((milestone, index) => <div className="timeline-item" key={milestone.id}><div className="timeline-rail"><span className={`timeline-node ${milestone.status}`}>{milestone.status === "completed" && <Check size={11} strokeWidth={3} />}</span>{index !== data.milestones.length - 1 && <span className={`timeline-line ${milestone.status === "completed" ? "filled" : ""}`} />}</div><div className="timeline-body"><div><strong>{milestone.title}</strong><span>{dateLabel(milestone.dueDate)}</span></div><p>{milestone.description}</p></div></div>)}</div><button className="card-bottom-link" onClick={() => navTo("Timeline")}>View full timeline <ArrowRight size={15} /></button></div>
            <div className="card team-card"><SectionHeading title="Team contribution" subtitle="The people behind the progress" action={<button className="text-action" onClick={() => navTo("Team")}>View team <ArrowRight size={15} /></button>} /><div className="contribution-list">{contribution.slice(0, 4).map(({ member, total, done }) => <div className="contribution-row" key={member.id}><Avatar person={member} size="small" /><span className="contribution-name">{member.name.split(" ")[0]}<small>{done}/{total} tasks</small></span><div className="mini-progress"><span style={{ width: `${total ? done / total * 100 : 0}%` }} /></div></div>)}</div></div></div></div>
        </>}

        {section === "My Tasks" && <div className="card full-card"><div className="list-header"><SectionHeading title="All project tasks" subtitle={`${data.tasks.length} tasks across your project`} action={<button className="button button-outline" onClick={requestNew}><Plus size={16} /> Add task</button>} /><div className="filter-bar">{["All tasks", "In progress", "To do", "Completed"].map((filter) => <button key={filter} className={taskFilter === filter ? "filter-active" : ""} onClick={() => setTaskFilter(filter)}>{filter}</button>)}</div></div><div className="task-table-head"><span>Task</span><span>Assignee</span><span>Due date</span><span>Status</span></div><div className="task-table">{visibleTasks.map((task) => <button className="task-table-row" key={task.id} onClick={() => openTask(task)}><span className="task-title-cell"><span className={`task-check ${task.status === "done" ? "complete" : ""}`}>{task.status === "done" && <Check size={12} />}</span><span><strong>{task.title}</strong><small>{task.category} · {task.priority} priority</small></span></span><span className="task-assignee"><Avatar person={data.members.find((member) => member.id === task.assigneeId)} size="small" />{data.members.find((member) => member.id === task.assigneeId)?.name ?? "Unassigned"}</span><span className={task.dueDate < today() && task.status !== "done" ? "overdue" : ""}>{dateLabel(task.dueDate, { month: "short", day: "numeric", year: "numeric" })}</span><span><span className={`table-status ${task.status}`}>{statusName[task.status]}</span></span></button>)}{visibleTasks.length === 0 && <div className="empty-state">No tasks match your search or filter.</div>}</div></div>}

        {section === "Timeline" && <div className="timeline-page"><div className="card timeline-overview"><div className="timeline-overview-icon"><Target size={25} /></div><div><span>THE BIG PICTURE</span><h2>From kickoff to launch</h2><p>Every milestone brings us closer to a better digital experience. Follow the journey below.</p></div><div className="timeline-overview-count"><strong>{data.milestones.filter((milestone) => milestone.status === "completed").length}/{data.milestones.length}</strong><small>milestones reached</small></div></div><div className="card milestone-card"><SectionHeading title="Project milestones" subtitle="Track each phase of the website redesign" /><div className="milestone-list">{data.milestones.map((milestone, index) => <div className="milestone-row" key={milestone.id}><div className="milestone-index">{String(index + 1).padStart(2, "0")}</div><span className={`milestone-check ${milestone.status}`}>{milestone.status === "completed" ? <Check size={18} /> : milestone.status === "current" ? <Circle size={13} fill="currentColor" /> : <Circle size={16} />}</span><div className="milestone-details"><strong>{milestone.title}</strong><p>{milestone.description}</p></div><span className="milestone-date"><CalendarDays size={15} />{dateLabel(milestone.dueDate, { month: "short", day: "numeric", year: "numeric" })}</span><span className={`table-status milestone-status ${milestone.status}`}>{milestone.status === "current" ? "In progress" : milestone.status}</span>{isLead && <select aria-label={`Change ${milestone.title} status`} value={milestone.status} onChange={(e) => act({ action: "updateMilestone", milestoneId: milestone.id, status: e.target.value }, "Milestone updated.")}><option value="upcoming">Upcoming</option><option value="current">In progress</option><option value="completed">Completed</option></select>}</div>)}</div></div></div>}

        {section === "Team" && <><div className="team-summary"><div className="card team-summary-card"><div className="summary-icon"><Users size={22} /></div><div><strong>{data.members.length}</strong><span>Team members</span></div></div><div className="card team-summary-card"><div className="summary-icon green"><CheckCheck size={22} /></div><div><strong>{completed}</strong><span>Tasks completed together</span></div></div><div className="card team-summary-card"><div className="summary-icon orange"><Activity size={22} /></div><div><strong>{progress}%</strong><span>Project completion</span></div></div></div><div className="card team-directory"><SectionHeading title="Meet the team" subtitle="Everyone contributing to Website Redesign" /><div className="member-grid">{contribution.map(({ member, total, done }) => <div className="member-card" key={member.id}><div className="member-top"><Avatar person={member} size="large" />{member.role === "lead" && <span className="lead-badge"><ShieldCheck size={12} /> Project lead</span>}</div><h3>{member.name}</h3><p>{member.title}</p><div className="member-stats"><span><strong>{total}</strong> assigned</span><span><strong>{done}</strong> completed</span></div><div className="member-progress"><span style={{ width: `${total ? done / total * 100 : 0}%` }} /></div></div>)}</div></div></>}

        {section === "Inbox" && <div className="card inbox-card"><SectionHeading title="Activity & alerts" subtitle="Deadline reminders and team completion updates" action={<span className="inbox-count">{unread} unread</span>} /><div className="inbox-list">{data.notifications.map((notice) => <button key={notice.id} className={`inbox-row ${notice.read || hiddenDeadlines.includes(notice.id) ? "read" : ""}`} onClick={() => readNotice(notice)}><span className={`inbox-icon ${notice.type}`}>{notice.type === "completion" ? <CheckCircle2 size={20} /> : notice.type === "deadline" ? <Clock3 size={20} /> : <Bell size={20} />}</span><span><strong>{notice.title}</strong><small>{notice.message}</small></span><span className="inbox-time">{notice.type === "deadline" ? "Upcoming" : "Team update"}</span>{!notice.read && !hiddenDeadlines.includes(notice.id) && <i />}</button>)}{data.notifications.length === 0 && <div className="empty-state">You're all caught up. No updates yet.</div>}</div></div>}

        <footer className="page-footer"><span>© {new Date().getFullYear()} Vertex Workspace</span><span>Made for better teamwork <span className="footer-heart">✦</span></span></footer>
      </div>
    </main>

    {showAuth && <div className="modal-backdrop" onMouseDown={() => setShowAuth(false)}><div className="modal auth-modal" onMouseDown={(e) => e.stopPropagation()}><button className="modal-close" onClick={() => setShowAuth(false)} aria-label="Close"><X size={19} /></button><div className="modal-symbol"><ShieldCheck size={24} /></div><h2>Welcome to Vertex</h2><p className="modal-subtitle">Sign in to manage tasks and collaborate with your team.</p><form onSubmit={login}><label>Email address<input type="email" value={authEmail} onChange={(e) => setAuthEmail(e.target.value)} required /></label><label>Password<input type="password" value={authPassword} onChange={(e) => setAuthPassword(e.target.value)} required /></label><button className="button button-primary modal-submit" disabled={busy}>Sign in <ArrowRight size={17} /></button></form><div className="demo-accounts"><strong>Demo access</strong><p>Use password <code>demo1234</code> for any account.</p><button onClick={() => { setAuthEmail("olivia@vertex.demo"); setAuthPassword("demo1234"); }}>Project lead · Olivia Rhye</button><button onClick={() => { setAuthEmail("phoenix@vertex.demo"); setAuthPassword("demo1234"); }}>Team member · Phoenix Baker</button></div></div></div>}

    {showNew && <div className="modal-backdrop" onMouseDown={() => setShowNew(false)}><div className="modal task-modal" onMouseDown={(e) => e.stopPropagation()}><button className="modal-close" onClick={() => setShowNew(false)} aria-label="Close"><X size={19} /></button><div className="modal-symbol"><Plus size={24} /></div><h2>Create a new task</h2><p className="modal-subtitle">Give your team a clear next step.</p><form onSubmit={createTask}><label>Task name<input placeholder="e.g. Design the pricing page" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} required maxLength={240} /></label><label>Description <span className="optional">Optional</span><textarea placeholder="Add a little more context..." value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} rows={3} /></label><div className="form-columns"><label>Assign to<select value={form.assigneeId} onChange={(e) => setForm({ ...form, assigneeId: e.target.value })}>{data.members.map((member) => <option key={member.id} value={member.id}>{member.name}</option>)}</select></label><label>Due date<input type="date" value={form.dueDate} onChange={(e) => setForm({ ...form, dueDate: e.target.value })} required /></label></div><div className="form-columns"><label>Category<select value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })}>{["Design", "Development", "Research", "Planning"].map((value) => <option key={value}>{value}</option>)}</select></label><label>Priority<select value={form.priority} onChange={(e) => setForm({ ...form, priority: e.target.value })}>{["low", "medium", "high"].map((value) => <option key={value} value={value}>{value[0].toUpperCase() + value.slice(1)}</option>)}</select></label></div><div className="modal-actions"><button type="button" className="button button-outline" onClick={() => setShowNew(false)}>Cancel</button><button className="button button-primary" disabled={busy}>Create task <ArrowRight size={17} /></button></div></form></div></div>}

    {selectedTask && <div className="modal-backdrop" onMouseDown={() => setSelectedTask(null)}><div className="modal task-modal" onMouseDown={(e) => e.stopPropagation()}><button className="modal-close" onClick={() => setSelectedTask(null)} aria-label="Close"><X size={19} /></button><div className="task-modal-eyebrow"><span className={`category-dot ${selectedTask.category.toLowerCase()}`} /> {selectedTask.category} <span>·</span> Task #{selectedTask.id}</div><h2>{selectedTask.title}</h2><p className="modal-subtitle">{selectedTask.description || "Manage the details and keep your team up to date."}</p><form onSubmit={saveTask}><label>Task name<input value={edit.title} onChange={(e) => setEdit({ ...edit, title: e.target.value })} disabled={!isLead} required /></label><div className="form-columns"><label>Assignee<select value={edit.assigneeId} onChange={(e) => setEdit({ ...edit, assigneeId: e.target.value })} disabled={!isLead}>{data.members.map((member) => <option key={member.id} value={member.id}>{member.name}</option>)}</select></label><label>Due date<input type="date" value={edit.dueDate} onChange={(e) => setEdit({ ...edit, dueDate: e.target.value })} disabled={!isLead} /></label></div><div className="form-columns"><label>Status<select value={edit.status} onChange={(e) => setEdit({ ...edit, status: e.target.value })} disabled={!user || (!isLead && selectedTask.assigneeId !== user.id)}><option value="todo">To do</option><option value="in_progress">In progress</option><option value="done">Completed</option></select></label><label>Priority<select value={edit.priority} onChange={(e) => setEdit({ ...edit, priority: e.target.value })} disabled={!isLead}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></label></div><div className="modal-actions"><div>{isLead && <button type="button" className="delete-button" onClick={async () => { if (window.confirm("Delete this task?")) { if (await act({ action: "deleteTask", taskId: selectedTask.id }, "Task deleted.")) setSelectedTask(null); } }}><Trash2 size={16} /> Delete</button>}</div><button type="button" className="button button-outline" onClick={() => setSelectedTask(null)}>Close</button>{user && (isLead || selectedTask.assigneeId === user.id) && <button className="button button-primary" disabled={busy}>Save changes</button>}{!user && <button type="button" className="button button-primary" onClick={() => { setSelectedTask(null); setShowAuth(true); }}>Sign in to edit</button>}</div></form></div></div>}
    {toast && <div className="toast"><CheckCircle2 size={17} />{toast}<button onClick={() => setToast("")}><X size={14} /></button></div>}
  </div>;
}
